# This file is auto-generated by LitServe.
# Disable auto-generation by setting `generate_client_file=False` in `LitServer.run()`.

import base64

import requests

# Read audio file and encode it in base64
with open(
    "/teamspace/studios/this_studio/sound_datasets/urbansound8k/audio/fold5/156869-8-0-5.wav",
    "rb",
) as f:
    audio_bytes = f.read()
    audio_b64 = base64.b64encode(audio_bytes).decode("utf-8")

response = requests.post("http://127.0.0.1:8000/predict", json={"audio_b64": audio_b64})
print(f"Status: {response.status_code}\nResponse:\n {response.text}")
